import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useUserStore } from "~/stores/useLocalUser";
// import Link from "next/link";
// import { useUserStore } from "~/stores/useLocalUser";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const createNewUser = api.user.create.useMutation();

  const searchLocalUser = api.user.userCheck.useQuery({
    userId: user.user?.id ?? "",
  });

  const firstName = useUserStore().firstName;
  const setFirstName = useUserStore().actions.setFirstName;

  console.log("searchLocalUser.", searchLocalUser.data);

  useEffect(() => {
    if (user.isSignedIn) {
      if (searchLocalUser.data && firstName !== searchLocalUser.data.name) {
        setFirstName(searchLocalUser.data.name);
      }
      if (user.user.firstName && user.user.firstName !== firstName) {
        console.log("HELLO FROM ABOUT TO CREATE AN USER ACCOUNT");
        createNewUser.mutate({
          name: user.user.firstName,
          userId: user.user.id,
        });
        setFirstName(user.user.firstName);
      }
    }
  }, [
    createNewUser,
    firstName,
    searchLocalUser.data,
    setFirstName,
    user.isSignedIn,
    user.user?.firstName,
    user.user?.id,
  ]);

  const router = useRouter();

  const onBtnClick = async () => {
    await router.push("/waiting");
  };

  return (
    <>
      <Head>
        <title>Pixelmate</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-white">
          <h1>Hello Welcome</h1>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <button onClick={onBtnClick} className="bg-sky-400 px-3 py-2">
          Ready
        </button>
      </main>
    </>
  );
}
